---
- name: Pip Installation
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install ruamel using pip
  ansible.builtin.pip:
    name: ruamel.yaml==0.17.21

- name: Upgrade sops using pip
  ansible.builtin.pip:
    name: sops
    state: latest